# Generated by Django 5.0.2 on 2024-03-04 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='fath_name',
            new_name='father_name',
        ),
    ]
